apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-green
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
      release: v2
  template:
    metadata:
      labels:
        app: demo-app
        release: v2
    spec:
      containers:
        - name: nginx
          image: httpd:alpine
          ports:
            - containerPort: 80